/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.simulador;

import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author galaipa
 */
public class PanelSimulador extends javax.swing.JPanel {

    /**
     * Creates new form Simulador
     */
    public PanelSimulador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JComboBox<String> comboCompañias = new JComboBox<>();
        JComboBox<String> comboTarifas = new JComboBox<>();
        JTextField textPotencia = new JTextField();
        JTextField textDias = new JTextField();
        JLabel labelCompañia = new JLabel();
        JLabel labelTarifa = new JLabel();
        JLabel labelPotenia = new JLabel();
        JLabel labelConsumo = new JLabel();
        JLabel labelDias = new JLabel();
        JButton buttonAñadir = new JButton();
        JLabel labelKW = new JLabel();
        JButton ayudaTarifa = new JButton();
        JButton ayudaPotencia = new JButton();
        JButton ayudaSelConsumo = new JButton();
        JButton ayudaDias = new JButton();
        JLabel labelPunta = new JLabel();
        JLabel labelValle = new JLabel();
        JLabel labelSuperValle = new JLabel();
        JTextField texPunta = new JTextField();
        JTextField textValle = new JTextField();
        JTextField textSuperValle = new JTextField();
        JLabel labelKW1 = new JLabel();
        JLabel labelKW2 = new JLabel();
        JLabel labelKW3 = new JLabel();
        JLabel labelTitulo = new JLabel();
        JButton ayudaSelConsumo1 = new JButton();
        JButton ayudaSelConsumo2 = new JButton();
        JButton buttonCargar = new JButton();

        comboCompañias.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        comboCompañias.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTarifas.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        comboTarifas.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textPotencia.setFont(new Font("Ubuntu", 0, 20)); // NOI18N

        textDias.setFont(new Font("Ubuntu", 0, 20)); // NOI18N

        labelCompañia.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelCompañia.setText("Compañia:");

        labelTarifa.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelTarifa.setText("Tarifa:");

        labelPotenia.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelPotenia.setText("Potencia:");

        labelConsumo.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelConsumo.setText("Consumo:");

        labelDias.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelDias.setText("Nº de dias:");

        buttonAñadir.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        buttonAñadir.setText("+");

        labelKW.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        labelKW.setText("Kw");

        ayudaTarifa.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaTarifa.setText("?");

        ayudaPotencia.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaPotencia.setText("?");

        ayudaSelConsumo.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaSelConsumo.setText("?");

        ayudaDias.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaDias.setText("?");

        labelPunta.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        labelPunta.setText("Punta:");

        labelValle.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        labelValle.setText("Valle:");

        labelSuperValle.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        labelSuperValle.setText("SuperValle:");

        labelKW1.setFont(new Font("Ubuntu", 0, 17)); // NOI18N
        labelKW1.setText("Kw/h");

        labelKW2.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        labelKW2.setText("Kw/h");

        labelKW3.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        labelKW3.setText("Kw/h");

        labelTitulo.setFont(new Font("Ubuntu", 1, 25)); // NOI18N
        labelTitulo.setText("Simulador de facturas");

        ayudaSelConsumo1.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaSelConsumo1.setText("?");

        ayudaSelConsumo2.setFont(new Font("Ubuntu", 0, 20)); // NOI18N
        ayudaSelConsumo2.setText("?");

        buttonCargar.setText("Cargar desde histórico");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCompañia)
                                    .addComponent(labelTarifa)
                                    .addComponent(labelPotenia)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelPunta)
                                        .addComponent(labelConsumo)
                                        .addComponent(labelValle)
                                        .addComponent(labelSuperValle)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTarifas, 0, 241, Short.MAX_VALUE)
                                    .addComponent(comboCompañias, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textPotencia, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(labelKW)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ayudaPotencia))
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonCargar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(textSuperValle, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textValle, GroupLayout.Alignment.LEADING))
                                                    .addGap(4, 4, 4))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(texPunta)
                                                    .addGap(2, 2, 2)))
                                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labelKW2)
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ayudaSelConsumo1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labelKW3)
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ayudaSelConsumo2))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labelKW1)
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ayudaSelConsumo))))))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAñadir)
                                    .addComponent(ayudaTarifa, GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDias)
                                .addGap(18, 18, 18)
                                .addComponent(textDias, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ayudaDias))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelTitulo)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCompañias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAñadir, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTarifas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayudaTarifa, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCompañia)
                        .addGap(18, 18, 18)
                        .addComponent(labelTarifa)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textPotencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPotenia)
                    .addComponent(labelKW)
                    .addComponent(ayudaPotencia, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsumo)
                    .addComponent(buttonCargar))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPunta)
                    .addComponent(texPunta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKW1)
                    .addComponent(ayudaSelConsumo, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValle)
                    .addComponent(textValle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKW2)
                    .addComponent(ayudaSelConsumo1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuperValle)
                    .addComponent(textSuperValle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKW3)
                    .addComponent(ayudaSelConsumo2, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textDias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDias)
                    .addComponent(ayudaDias, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
