/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.anadirCompania;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;

/**
 *
 * @author asier
 */
public class AñadirCompañia extends javax.swing.JPanel {

    /**
     * Creates new form AñadirCompañia
     */
    public AñadirCompañia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel panelNombre = new JPanel();
        JLabel labelNombre = new JLabel();
        JPanel panelDatos = new JPanel();
        JLabel labelNombreCompania = new JLabel();
        JTextField txNombreCompania = new JTextField();
        JLabel labelTarifa = new JLabel();
        JScrollPane listaTarifas = new JScrollPane();
        JList<String> jList1 = new JList<>();
        JButton btAnadir = new JButton();
        JButton btGuardar = new JButton();
        JButton btCancelar = new JButton();

        setMaximumSize(new Dimension(400, 418));
        setMinimumSize(new Dimension(400, 418));
        setPreferredSize(new Dimension(400, 418));

        panelNombre.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombre.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setForeground(new Color(16, 103, 218));
        labelNombre.setHorizontalAlignment(SwingConstants.CENTER);
        labelNombre.setText("AÑADIR COMPAÑÍA");

        GroupLayout panelNombreLayout = new GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(labelNombre)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNombreLayout.setVerticalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.setBackground(new Color(190, 191, 190));
        panelDatos.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        panelDatos.setMaximumSize(new Dimension(400, 366));
        panelDatos.setMinimumSize(new Dimension(400, 366));

        labelNombreCompania.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombreCompania.setForeground(new Color(1, 1, 1));
        labelNombreCompania.setText("Nombre Compañía: ");

        txNombreCompania.setText("nombreCompañía");

        labelTarifa.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelTarifa.setForeground(new Color(1, 1, 1));
        labelTarifa.setText("Tarifas: ");

        jList1.setBackground(new Color(242, 241, 240));
        jList1.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        jList1.setForeground(new Color(1, 1, 1));
        jList1.setModel(new AbstractListModel<String>() {
            String[] strings = { "Tarifa 1", "Tarifa 2", "Tarifa 3", "Tarifa 4", "Tarifa 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTarifas.setViewportView(jList1);

        btAnadir.setText("Añadir");
        btAnadir.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btGuardar.setText("Guardar");
        btGuardar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btCancelar.setText("Cancelar");
        btCancelar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout panelDatosLayout = new GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTarifa)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelNombreCompania)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txNombreCompania, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btGuardar, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE))
                            .addComponent(listaTarifas)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btAnadir, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCompania)
                    .addComponent(txNombreCompania, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTarifa)
                .addGap(12, 12, 12)
                .addComponent(listaTarifas, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAnadir)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelNombre, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
