/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.iniciarSesion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.BevelBorder;

/**
 *
 * @author asier
 */
public class IniciarSesion extends javax.swing.JPanel {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel panelIniciarSesion = new JPanel();
        JLabel labelIniciarSesion = new JLabel();
        JPanel panelCentro = new JPanel();
        JLabel labelUsuario = new JLabel();
        JLabel labelContrasena = new JLabel();
        JPasswordField txContraseña = new JPasswordField();
        JTextField txUsuario = new JTextField();
        JButton btAceptar = new JButton();
        JButton btCancelar = new JButton();
        JLabel labelPregunta = new JLabel();
        JButton btRegistrarse = new JButton();

        setBackground(new Color(190, 191, 190));
        setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        setMaximumSize(new Dimension(562, 418));
        setMinimumSize(new Dimension(562, 418));
        setPreferredSize(new Dimension(562, 418));

        panelIniciarSesion.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelIniciarSesion.setBackground(new Color(54, 136, 215));
        labelIniciarSesion.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelIniciarSesion.setForeground(new Color(16, 103, 218));
        labelIniciarSesion.setText("INICIAR SESIÓN");

        GroupLayout panelIniciarSesionLayout = new GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(panelIniciarSesionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(labelIniciarSesion)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIniciarSesionLayout.setVerticalGroup(panelIniciarSesionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIniciarSesion)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentro.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelUsuario.setFont(new Font("DialogInput", 1, 16)); // NOI18N
        labelUsuario.setText("Nombre de usuario: ");
        labelUsuario.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelContrasena.setFont(new Font("DialogInput", 1, 16)); // NOI18N
        labelContrasena.setText("Contraseña: ");
        labelContrasena.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        txContraseña.setText("contraseña");

        txUsuario.setText("NombreUsuario");

        btAceptar.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        btAceptar.setForeground(new Color(1, 1, 1));
        btAceptar.setText("Aceptar");
        btAceptar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        btAceptar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btCancelar.setForeground(new Color(1, 1, 1));
        btCancelar.setText("Cancelar");
        btCancelar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout panelCentroLayout = new GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(btAceptar, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelContrasena, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario))
                .addGap(34, 34, 34)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txUsuario, GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txContraseña))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCentroLayout.setVerticalGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txUsuario, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelContrasena, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txContraseña, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        labelPregunta.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelPregunta.setForeground(new Color(1, 1, 1));
        labelPregunta.setText("¿No estas registrado?");

        btRegistrarse.setForeground(new Color(1, 1, 1));
        btRegistrarse.setText("Registrarse");
        btRegistrarse.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelCentro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIniciarSesion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(labelPregunta)
                .addGap(18, 18, 18)
                .addComponent(btRegistrarse, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIniciarSesion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCentro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPregunta)
                    .addComponent(btRegistrarse, GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
