/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrarse;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.border.BevelBorder;

/**
 *
 * @author asier
 */
public class Registrarse extends javax.swing.JPanel {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel panelRegistrarse = new JPanel();
        JLabel labelRegistrarse = new JLabel();
        JPanel panelDatos = new JPanel();
        JLabel labelNombre = new JLabel();
        JLabel labelApellido = new JLabel();
        JLabel labelNombreUsuario = new JLabel();
        JLabel labelContrasena = new JLabel();
        JLabel labelRepetirContrasena = new JLabel();
        JTextField txNombre = new JTextField();
        JTextField txApellido = new JTextField();
        JTextField txNombreUsuario = new JTextField();
        JPasswordField txContrasena = new JPasswordField();
        JPasswordField txRContrasena = new JPasswordField();
        JButton btRegistrarse = new JButton();
        JButton btCancelar = new JButton();
        JLabel labelNombre1 = new JLabel();
        JLabel labelNombre2 = new JLabel();
        jComboBox1 = new JComboBox<>();
        jComboBox2 = new JComboBox<>();

        setBackground(new Color(190, 191, 190));
        setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        setMaximumSize(new Dimension(562, 418));
        setMinimumSize(new Dimension(562, 418));
        setPreferredSize(new Dimension(562, 418));

        panelRegistrarse.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelRegistrarse.setBackground(new Color(54, 136, 215));
        labelRegistrarse.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelRegistrarse.setForeground(new Color(16, 103, 218));
        labelRegistrarse.setText("REGISTRARSE");

        GroupLayout panelRegistrarseLayout = new GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(panelRegistrarseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(labelRegistrarse)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistrarseLayout.setVerticalGroup(panelRegistrarseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrarse)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombre.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombre.setText("Nombre: ");
        labelNombre.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelApellido.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelApellido.setText("Apellido:");
        labelApellido.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelNombreUsuario.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombreUsuario.setText("Nombre de usuario: ");
        labelNombreUsuario.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelContrasena.setFont(new Font("Ubuntu", 1, 16)); // NOI18N
        labelContrasena.setText("Contraseña:");
        labelContrasena.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelRepetirContrasena.setFont(new Font("Ubuntu", 1, 16)); // NOI18N
        labelRepetirContrasena.setText("Repetir contraseña:");
        labelRepetirContrasena.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        txNombre.setText("nombre");

        txApellido.setText("apellido");

        txNombreUsuario.setText("nombreUsuario");

        txContrasena.setText("contraseña");

        txRContrasena.setText("contraseña");
        txRContrasena.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txRContrasenaActionPerformed(evt);
            }
        });

        btRegistrarse.setText("Registrarse");

        btCancelar.setText("Cancelar");

        labelNombre1.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombre1.setText("Compañía: ");
        labelNombre1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelNombre2.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombre2.setText("Tarifa: ");
        labelNombre2.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GroupLayout panelDatosLayout = new GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelNombreUsuario, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txNombreUsuario, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelApellido, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNombre, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txNombre, GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txApellido)))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelContrasena)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txContrasena, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelRepetirContrasena)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txRContrasena, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btRegistrarse, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelNombre1)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNombre2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellido, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUsuario, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNombreUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRepetirContrasena)
                        .addComponent(txRContrasena, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(txContrasena, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelContrasena))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrarse)
                    .addComponent(btCancelar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistrarse, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistrarse, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txRContrasenaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txRContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRContrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    // End of variables declaration//GEN-END:variables
}
