package pobl4.presentacion.anadirCompania;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

import pobl4.dominio.Precio;
import pobl4.dominio.Tarifa;
import pobl4.negocio.CtrlAnadirTarifa;

public class VistaAnadirTarifa extends javax.swing.JDialog {
	CtrlAnadirTarifa controlador;
	JList<Precio> lista;
	Tarifa tarifa;
	
    public VistaAnadirTarifa(JDialog vista, boolean modal, CtrlAnadirTarifa controlador,Tarifa tarifa) {
        super(vista, modal);
        this.controlador = controlador;
        this.tarifa = tarifa;
        controlador.setVista(this);
        initComponents();
        addListeners();
        this.setVisible(true);
    }
    
    public void addListeners() {
    	addListener(btAnadir,"anadir");
    	addListener(btCancelar,"cancelar");
    	addListener(btGuardar,"guardar");
    }
    
    public void addListener(JButton button, String actionCommand) {
    	button.addActionListener(controlador);
    	button.setActionCommand(actionCommand);
    }
    
    public String getDescripcionTarifa() {
    	return txNombreTarifa.getText();
    }
    
    public void actualizarListaPrecios() {
    	lista = new JList<>(tarifa.getPrecios().toArray(new Precio[0]));
    	panelLista.setViewportView(lista);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JPanel panelNombre = new JPanel();
        JLabel labelNombre = new JLabel();
        JPanel panelDatos = new JPanel();
        JLabel labelNombreTarifa = new JLabel();
        txNombreTarifa = new JTextField();
        JLabel labelTramo = new JLabel();
        btGuardar = new JButton();
        btAnadir = new JButton();
        btCancelar = new JButton();
        panelLista = new JScrollPane();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new Dimension(400, 418));
        jPanel1.setMinimumSize(new Dimension(400, 418));

        panelNombre.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombre.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setForeground(new Color(16, 103, 218));
        labelNombre.setHorizontalAlignment(SwingConstants.CENTER);
        labelNombre.setText("AÑADIR TARIFA");

        GroupLayout panelNombreLayout = new GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(labelNombre)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        panelNombreLayout.setVerticalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.setBackground(new Color(190, 191, 190));
        panelDatos.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombreTarifa.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelNombreTarifa.setForeground(new Color(1, 1, 1));
        labelNombreTarifa.setText("Nombre Tarifa: ");

        txNombreTarifa.setText("nombreTarifa");
        txNombreTarifa.setMaximumSize(new Dimension(400, 418));
        txNombreTarifa.setMinimumSize(new Dimension(400, 418));

        labelTramo.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelTramo.setForeground(new Color(1, 1, 1));
        labelTramo.setText("Tramos: ");

        btGuardar.setText("Guardar");
        btGuardar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btAnadir.setText("Añadir");
        btAnadir.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btCancelar.setText("Cancelar");
        btCancelar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout panelDatosLayout = new GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btAnadir, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btGuardar, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelLista, GroupLayout.PREFERRED_SIZE, 321, GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTramo)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(labelNombreTarifa)
                        .addGap(18, 18, 18)
                        .addComponent(txNombreTarifa, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreTarifa)
                    .addComponent(txNombreTarifa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTramo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLista, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAnadir)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btCancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelNombre, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btAnadir;
    JButton btCancelar;
    JButton btGuardar;
    JScrollPane panelLista;
    JTextField txNombreTarifa;
    // End of variables declaration//GEN-END:variables
}
