package pobl4.presentacion.anadirCompania;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import org.jdesktop.xswingx.PromptSupport;

import pobl4.dominio.Precio;
import pobl4.negocio.CtrlAnadirPrecio;


public class VistaAnadirTramo extends javax.swing.JDialog {
	CtrlAnadirPrecio controlador;
	
    public VistaAnadirTramo(JDialog parent, boolean modal, CtrlAnadirPrecio controlador) {
        super(parent, modal);
        this.controlador = controlador;
        controlador.setVista(this);
        initComponents();
        addPromptText();
        addListeners();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void addListeners() {
    	btGuardar.addActionListener(controlador);
    	btGuardar.setActionCommand("anadir");
    	btCancelar.addActionListener(controlador);
    	btCancelar.setActionCommand("cancelar");
    }
    
    public int getHoraInicio() {
    	return Integer.parseInt(txHoraInicio.getText());
    }
    
    public int getHoraFin() {
    	return Integer.parseInt(txHoraFin.getText());
    }
    
    public int getMesInicio() {
    	return Integer.parseInt(txMesInicio.getText());
    } 
    
    public int getMesFin() {
    	return Integer.parseInt(txMesFin.getText());
    } 
    
    public double getPrecio() {
    	return Double.parseDouble(txPrecio.getText());
    }
    
    public void mostrarError() {
    	JOptionPane.showMessageDialog(this, "Solo valores númericos","Error",JOptionPane.WARNING_MESSAGE);
    }
    
       public void addPromptText() {
    	PromptSupport.setPrompt("horaInicio", txHoraInicio);
    	PromptSupport.setPrompt("horaFin", txHoraFin);
        PromptSupport.setPrompt("mesInicio", txMesInicio);
        PromptSupport.setPrompt("mesFin", txMesFin);
        PromptSupport.setPrompt("precio", txPrecio);
    	
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JPanel panelNombre = new JPanel();
        JLabel labelNombre = new JLabel();
        JPanel panelDatos = new JPanel();
        JLabel labelHoraInicio = new JLabel();
        JLabel labelMesInicio = new JLabel();
        JLabel labelHoraFin = new JLabel();
        JLabel labelMesFin = new JLabel();
        JLabel labelPrecio = new JLabel();
        txHoraInicio = new JTextField();
        txHoraFin = new JTextField();
        txMesInicio = new JTextField();
        txMesFin = new JTextField();
        txPrecio = new JTextField();
        btCancelar = new JButton();
        btGuardar = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new Dimension(400, 418));
        jPanel1.setMinimumSize(new Dimension(400, 418));

        panelNombre.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombre.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setForeground(new Color(16, 103, 218));
        labelNombre.setHorizontalAlignment(SwingConstants.CENTER);
        labelNombre.setText("AÑADIR TRAMO");

        GroupLayout panelNombreLayout = new GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelNombreLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNombre)
                .addGap(134, 134, 134))
        );
        panelNombreLayout.setVerticalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelNombreLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNombre)
                .addContainerGap())
        );

        panelDatos.setBackground(new Color(190, 191, 190));
        panelDatos.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelHoraInicio.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelHoraInicio.setForeground(new Color(1, 1, 1));
        labelHoraInicio.setText("Hora inicio: ");

        labelMesInicio.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelMesInicio.setForeground(new Color(1, 1, 1));
        labelMesInicio.setText("Mes inicio: ");

        labelHoraFin.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelHoraFin.setForeground(new Color(1, 1, 1));
        labelHoraFin.setText("Hora fin: ");

        labelMesFin.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelMesFin.setForeground(new Color(1, 1, 1));
        labelMesFin.setText("Mes fin: ");

        labelPrecio.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelPrecio.setForeground(new Color(1, 1, 1));
        labelPrecio.setText("Precio: ");

        txHoraFin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txHoraFinActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btGuardar.setText("Guardar");
        btGuardar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout panelDatosLayout = new GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrecio)
                    .addComponent(labelMesFin)
                    .addComponent(labelMesInicio)
                    .addComponent(labelHoraFin)
                    .addComponent(labelHoraInicio))
                .addGap(40, 40, 40)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txHoraInicio, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txHoraFin, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMesInicio, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMesFin, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPrecio, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btGuardar, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoraInicio)
                    .addComponent(txHoraInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoraFin)
                    .addComponent(txHoraFin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesInicio)
                    .addComponent(txMesInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesFin)
                    .addComponent(txMesFin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(txPrecio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btGuardar))
                .addGap(25, 25, 25))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelNombre, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txHoraFinActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txHoraFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHoraFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btCancelar;
    JButton btGuardar;
    JTextField txHoraFin;
    JTextField txHoraInicio;
    JTextField txMesFin;
    JTextField txMesInicio;
    JTextField txPrecio;
    // End of variables declaration//GEN-END:variables
}
