/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.presentacion;

import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import javax.swing.DefaultComboBoxModel;

import org.jfree.chart.ChartPanel;

import pobl4.dao.ConsumoDAO;
import pobl4.dao.UserDAO;
import pobl4.dominio.Consumo;
import pobl4.negocio.CtrlConsumo;
import pobl4.negocio.CtrlMain;
import pobl4.negocio.GraficoFactory;

/**
 *
 * @author asier
 */
public class VistaConsumo extends javax.swing.JDialog implements ItemListener{
    
    CtrlConsumo controlador;
    List<Consumo> listaConsumos;
    DefaultComboBoxModel<String> model1;
    DefaultComboBoxModel<String> model2;
    DefaultComboBoxModel<String> model3;
    ChartPanel chartPanel;
    /**
     * 
     * @param parent
     * @param modal
     * @param listConsumo
     * @param consumoDAO
     */
    public VistaConsumo(java.awt.Frame parent, boolean modal,List<Consumo> listConsumo,ConsumoDAO consumoDAO,UserDAO userDAO,CtrlMain main) {
        super(parent, modal);
        initComponents();
        this.listaConsumos = listConsumo;
        controlador = new CtrlConsumo(this,listConsumo,consumoDAO,userDAO,main);
        initFiltros();
        addBtListeners();
        this.setResizable(true);
        this.setVisible(true);
        
    }

    public List<Consumo> getConsumos(){
    	return listaConsumos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        panelArriba = new javax.swing.JPanel();
        btAno = new javax.swing.JButton();
        btHora = new javax.swing.JButton();
        btDia = new javax.swing.JButton();
        btMes = new javax.swing.JButton();
        btAnadir = new javax.swing.JButton();
        panelDerecha = new javax.swing.JPanel();
        datosEstadisticos = new javax.swing.JLabel();
        periodoTiempo1 = new javax.swing.JLabel();
        fechaAno = new javax.swing.JComboBox<>();
        fechaMes = new javax.swing.JComboBox<>();
        labelConsumo = new javax.swing.JLabel();
        labelPunta = new javax.swing.JLabel();
        labelValle = new javax.swing.JLabel();
        labelMedia = new javax.swing.JLabel();
        consumo = new javax.swing.JLabel();
        punta = new javax.swing.JLabel();
        valle = new javax.swing.JLabel();
        mediaDia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaDia = new javax.swing.JComboBox<>();
        btCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(905, 565));
        setMinimumSize(new java.awt.Dimension(905, 565));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(905, 565));

        jPanel1.setMaximumSize(new java.awt.Dimension(905, 565));
        jPanel1.setMinimumSize(new java.awt.Dimension(905, 565));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(16, 103, 218));
        labelNombre.setText("CONSUMO HISTÓRICO");

        javax.swing.GroupLayout panelNombreLayout = new javax.swing.GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addComponent(labelNombre)
                .addGap(365, 365, 365))
        );
        panelNombreLayout.setVerticalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelArriba.setBackground(new java.awt.Color(190, 191, 190));
        panelArriba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btAno.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btAno.setText("Año");
        btAno.setActionCommand("Ano");
        btAno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btHora.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btHora.setText("Hora");
        btHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btDia.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btDia.setText("Día");
        btDia.setActionCommand("Dia");
        btDia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btMes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btMes.setText("Mes");
        btMes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAnadir.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btAnadir.setText("+");
        btAnadir.setActionCommand("Anadir");
        btAnadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelArribaLayout = new javax.swing.GroupLayout(panelArriba);
        panelArriba.setLayout(panelArribaLayout);
        panelArribaLayout.setHorizontalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btAno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btHora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(btAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panelArribaLayout.setVerticalGroup(
            panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHora)
                    .addComponent(btDia)
                    .addComponent(btMes)
                    .addComponent(btAno)
                    .addComponent(btAnadir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDerecha.setBackground(new java.awt.Color(190, 191, 190));
        panelDerecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        datosEstadisticos.setBackground(new java.awt.Color(1, 1, 1));
        datosEstadisticos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        datosEstadisticos.setForeground(new java.awt.Color(1, 1, 1));
        datosEstadisticos.setText("DATOS ESTADÍSTICOS");

        periodoTiempo1.setBackground(new java.awt.Color(1, 1, 1));
        periodoTiempo1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        periodoTiempo1.setForeground(new java.awt.Color(1, 1, 1));
        periodoTiempo1.setText("Periodo de tiempo");

        labelConsumo.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        labelConsumo.setForeground(new java.awt.Color(1, 1, 1));
        labelConsumo.setText("Consumo Medio: ");

        labelPunta.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        labelPunta.setForeground(new java.awt.Color(1, 1, 1));
        labelPunta.setText("Periodo Punta Medio: ");

        labelValle.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        labelValle.setForeground(new java.awt.Color(1, 1, 1));
        labelValle.setText("Periodo Valle Medio: ");

        labelMedia.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        labelMedia.setForeground(new java.awt.Color(1, 1, 1));
        labelMedia.setText("Media por día: ");

        consumo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        consumo.setText("0");

        punta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        punta.setText("0");

        valle.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        valle.setText("0");

        mediaDia.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        mediaDia.setText("0");

        jLabel1.setText("Año");

        jLabel2.setText("Mes");

        jLabel3.setText("Día");



        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                        .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addComponent(periodoTiempo1)
                                .addGap(27, 27, 27))
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDerechaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(fechaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDerechaLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(datosEstadisticos))
                                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                        .addComponent(labelMedia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mediaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                        .addComponent(labelValle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(valle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                        .addComponent(labelConsumo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                        .addComponent(labelPunta)
                                        .addGap(42, 42, 42)
                                        .addComponent(punta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                        .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(periodoTiempo1)
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(datosEstadisticos)
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsumo)
                    .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPunta)
                    .addComponent(punta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValle)
                    .addComponent(valle, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedia)
                    .addComponent(mediaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btCalcular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 595, Short.MAX_VALUE)
                .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 317, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 114, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCalcularActionPerformed

    public void addBtListeners(){
        btAnadir.addActionListener(controlador);
        btAno.addActionListener(controlador);
        btDia.addActionListener(controlador);
        btHora.addActionListener(controlador);
        btMes.addActionListener(controlador);
        fechaAno.addItemListener(this);
        fechaMes.addItemListener(this);
        if(listaConsumos.isEmpty()) return;
        fechaAno.setModel(model1);
        fechaMes.setModel(model2);
        fechaDia.setModel(model3);

        
    }

    public void setGrafico(Map<String, Double> map) {
    	if(chartPanel != null) { 
    		chartPanel.removeAll();
    		jPanel2.remove(chartPanel);}
    	chartPanel = GraficoFactory.getGraficoBarras(map);
    	chartPanel.setSize(jPanel1.getSize());
    	jPanel2.add(chartPanel,BorderLayout.CENTER);
    	this.repaint();
    }
  
    
    public int getAño() {
    	return Integer.valueOf(fechaAno.getSelectedItem().toString());
    }
    public int getMes() {
    	return Integer.valueOf(fechaMes.getSelectedItem().toString());
    }
    public int getDia() {
    	return Integer.valueOf(fechaDia.getSelectedItem().toString());
    }
    
    public void initFiltros() {
    	model1 = new DefaultComboBoxModel<>(getFechasInicio());
    	if(model1.getSelectedItem()== null) return;
    	Object [] params1 = {"ano",Integer.valueOf((String)model1.getSelectedItem())};
    	UpdateFiltros(params1);
    	Object [] params2 = {"mes", Integer.valueOf((String)model2.getSelectedItem())};
    	UpdateFiltros(params2);
    	
    	
    }
    
    public void UpdateFiltros(Object...params) {
    	String periodo = (String)params[0];
    	int periodoReferencia = (int) params[1];
    	
    	System.out.println(periodo+periodoReferencia);
    	if(periodo.equals("ano")) {
    		model2 = new DefaultComboBoxModel<>(getMesesPorAno(periodoReferencia));
    		fechaMes.setModel(model2);
    	}else if(periodo.equals("mes")) {
    		model3 = new DefaultComboBoxModel<>(getDiasPorMes(periodoReferencia));
    		fechaDia.setModel(model3);
    	}
    	
    	this.repaint();
    }
    private String [] getDiasPorMes(int mes) {
    	List<String> fechasFin = new ArrayList<>();
    	for(Consumo c: listaConsumos) {
    		if(c.getMes() == mes && !fechasFin.contains(String.valueOf(c.getDia())))
    			fechasFin.add(String.valueOf(c.getDia()));
    	}
    	
    	Collections.sort(fechasFin, new Comparator<String>() {

			@Override
			public int compare(String o1, String o2) {
				// TODO Auto-generated method stub
				return Integer.valueOf(o1) < Integer.valueOf(o2)?-1:Integer.valueOf(o1) > Integer.valueOf(o2)?1:0;
			}
		});
    	return fechasFin.toArray(new String [0]);
	}

	private String [] getMesesPorAno(int ano) {
    	List<String> fechasFin = new ArrayList<>();
    	for(Consumo c: listaConsumos) {
    		if(c.getAño() == ano && !fechasFin.contains(String.valueOf(c.getMes())))
    			fechasFin.add(String.valueOf(c.getMes()));
    	}
    	
    	Collections.sort(fechasFin, new Comparator<String>() {

			@Override
			public int compare(String o1, String o2) {
				// TODO Auto-generated method stub
				return Integer.valueOf(o1) < Integer.valueOf(o2)?-1:Integer.valueOf(o1) > Integer.valueOf(o2)?1:0;
			}
		});
    	return fechasFin.toArray(new String [0]);
	}

	public String [] getFechasInicio() {
    	List<String> fechasInicio = new ArrayList<>();
    	for(Consumo c: listaConsumos) {
    		if(!fechasInicio.contains(String.valueOf(c.getAño())))
    			fechasInicio.add(String.valueOf(c.getAño()));
    	}
    	Collections.sort(fechasInicio, new Comparator<String>() {

			@Override
			public int compare(String o1, String o2) {
				// TODO Auto-generated method stub
				return Integer.valueOf(o1) < Integer.valueOf(o2)?-1:Integer.valueOf(o1) > Integer.valueOf(o2)?1:0;
			}
		});
    	return fechasInicio.toArray(new String [0]);
    }
	
	public void setEstadisticos(Map<String,Double> datosEstadisticos) {
		consumo.setText(String.valueOf(datosEstadisticos.get("consumoMedio")));
		punta.setText(String.valueOf(datosEstadisticos.get("periodoPunta")));
		valle.setText(String.valueOf(datosEstadisticos.get("periodoValle")));		
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadir;
    private javax.swing.JButton btAno;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btDia;
    private javax.swing.JButton btHora;
    private javax.swing.JButton btMes;
    private javax.swing.JLabel consumo;
    private javax.swing.JLabel datosEstadisticos;
    private javax.swing.JComboBox<String> fechaDia;
    private javax.swing.JComboBox<String> fechaMes;
    private javax.swing.JComboBox<String> fechaAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelConsumo;
    private javax.swing.JLabel labelMedia;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPunta;
    private javax.swing.JLabel labelValle;
    private javax.swing.JLabel mediaDia;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JLabel periodoTiempo1;
    private javax.swing.JLabel punta;
    private javax.swing.JLabel valle;
    // End of variables declaration//GEN-END:variables
	@Override
	public void itemStateChanged(ItemEvent e) {
		if(e.getStateChange() == e.SELECTED) {
			if(e.getSource() == fechaAno) {
				Object [] params = {"ano", Integer.valueOf((String) model1.getSelectedItem())};
				UpdateFiltros(params);
			}else if(e.getSource() == fechaMes) {
				Object [] params = {"mes", Integer.valueOf((String) model2.getSelectedItem())};
				UpdateFiltros(params);
			}
		}
	}
}
