/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.presentacion;

import java.awt.BorderLayout;
import java.awt.Container;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import pobl4.negocio.CtrlMain;

/**
 *
 * @author asier
 */
public class VistaMain extends javax.swing.JFrame {

	public static int USERID = 0;

	public static final long serialVersionUID = 1L;
	CtrlMain controlador;
	
    /**
     * Creates new form VistaMain
     */
    public VistaMain() {
    	controlador = new CtrlMain(this);
        //initComponents();
    	this.setTitle("zazpi");
    	this.setSize(1280, 768);
    	this.setContentPane(mainPane());
    	this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	this.setVisible(true);
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		VistaMain main = new VistaMain();
		System.err.println("Everything ok chief!");
                
	}
	
	public Container mainPane() {
		JPanel pane = new JPanel(new BorderLayout());
		JButton consumo = new JButton("Mi Consumo");
		consumo.setActionCommand("consumo");
		consumo.addActionListener(controlador);
		pane.add(consumo, BorderLayout.CENTER);
		
		
		return pane;
	}
}
