/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.presentacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

import org.jdesktop.xswingx.PromptSupport;

import pobl4.dao.UserDAO;
import pobl4.dominio.Compania;
import pobl4.dominio.Tarifa;
import pobl4.dominio.User;
import pobl4.negocio.CtrlLogin;
import pobl4.utils.Utils;

/**
 *
 * @author galaipa
 */
public class VistaLogin extends javax.swing.JDialog{
    CtrlLogin controlador;
    User user;
    UserDAO userDAO;
    List<Compania> listaCompania;
    List<Tarifa> listaTarifas;
    /**
     * Creates new form VistaLogin1
     */
    public VistaLogin(java.awt.Frame parent, boolean modal,UserDAO userDAO,List<Compania> listaCompania,List<Tarifa> listaTarifas) {
        super(parent, modal);
        initComponents();
        this.listaCompania = listaCompania;
        this.listaTarifas = listaTarifas;
        this.userDAO = userDAO;
        controlador = new CtrlLogin(this,userDAO);
        addPromptText();
        addListeners();
        this.setVisible(true);
    }
    
    public List<Compania> getListCompanias(){
    	return listaCompania;
    }
    
    public List<Tarifa> getListTarifas(){
    	return listaTarifas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JPanel panelIniciarSesion = new JPanel();
        JLabel labelIniciarSesion = new JLabel();
        JPanel panelCentro = new JPanel();
        JLabel labelUsuario = new JLabel();
        JLabel labelContrasena = new JLabel();
        txContraseña = new JPasswordField();
        txUsuario = new JTextField();
        btEntrar = new JButton();
        JLabel labelPregunta = new JLabel();
        btRegistrarse = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new Color(190, 191, 190));
        jPanel1.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        jPanel1.setMaximumSize(new Dimension(562, 418));
        jPanel1.setMinimumSize(new Dimension(562, 418));

        panelIniciarSesion.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelIniciarSesion.setBackground(new Color(54, 136, 215));
        labelIniciarSesion.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        labelIniciarSesion.setForeground(new Color(16, 103, 218));
        labelIniciarSesion.setText("INICIAR SESIÓN");

        GroupLayout panelIniciarSesionLayout = new GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(panelIniciarSesionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(labelIniciarSesion)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIniciarSesionLayout.setVerticalGroup(panelIniciarSesionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIniciarSesion)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentro.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelUsuario.setFont(new Font("DialogInput", 1, 16)); // NOI18N
        labelUsuario.setText("Nombre de usuario: ");
        labelUsuario.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        labelContrasena.setFont(new Font("DialogInput", 1, 16)); // NOI18N
        labelContrasena.setText("Contraseña: ");
        labelContrasena.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        btEntrar.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        btEntrar.setForeground(new Color(1, 1, 1));
        btEntrar.setText("Entrar");
        btEntrar.setActionCommand("entrar");
        btEntrar.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout panelCentroLayout = new GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentroLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrasena, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario))
                        .addGap(34, 34, 34)
                        .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(txUsuario, GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txContraseña)))
                    .addGroup(panelCentroLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btEntrar, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelCentroLayout.setVerticalGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txUsuario, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panelCentroLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelContrasena, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txContraseña, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btEntrar, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        labelPregunta.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelPregunta.setForeground(new Color(1, 1, 1));
        labelPregunta.setText("¿No estas registrado?");

        btRegistrarse.setForeground(new Color(1, 1, 1));
        btRegistrarse.setText("Registrarse");
        btRegistrarse.setActionCommand("registro");
        btRegistrarse.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelCentro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIniciarSesion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(labelPregunta)
                .addGap(18, 18, 18)
                .addComponent(btRegistrarse, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIniciarSesion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCentro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPregunta)
                    .addComponent(btRegistrarse, GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addListeners(){
        btEntrar.addActionListener(controlador);
        btRegistrarse.addActionListener(controlador);
        btEntrar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"enter_pressed");
        btEntrar.getActionMap().put("enter_pressed", Utils.getHandlerLoginKeyEvent(userDAO, this));
    }

    public String getTxContraseña() {
        String password = new String(txContraseña.getPassword());
        return password;
    }

    public String getTxUsuario() {
        return txUsuario.getText();
    }
    
    public void closeDialog(User user){
        this.user = user;
        this.dispose();
    }
    
    public User getUser (){
        return user;
    }
    
    public void addPromptText() {
    	PromptSupport.setPrompt("password", txContraseña);
    	PromptSupport.setPrompt("username", txUsuario);
    	
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btEntrar;
    JButton btRegistrarse;
    JPasswordField txContraseña;
    JTextField txUsuario;
    // End of variables declaration//GEN-END:variables

}
