/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pobl4.presentacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author asier
 */
public class VistaComparador extends javax.swing.JPanel {

    /**
     * Creates new form CompararTarifas
     */
    public VistaComparador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel panelArriba = new JPanel();
        JButton btMes = new JButton();
        JButton btDia = new JButton();
        JButton btHora = new JButton();
        JButton btAnadir = new JButton();
        JButton btAno = new JButton();
        JPanel panelDerecha = new JPanel();
        JLabel periodoTiempo = new JLabel();
        JComboBox<String> fechaInicio = new JComboBox<>();
        JComboBox<String> fechaFin = new JComboBox<>();
        JLabel tipoTarifa = new JLabel();
        JCheckBox sinDiscriminacion = new JCheckBox();
        JCheckBox discriminacion1 = new JCheckBox();
        JCheckBox discriminacion2 = new JCheckBox();
        JLabel renovable = new JLabel();
        JCheckBox soloRenovable = new JCheckBox();
        JScrollPane panelIzquierda = new JScrollPane();
        JList<String> listaCompanias = new JList<>();
        JPanel panelNombre = new JPanel();
        JLabel labelNombre = new JLabel();

        setMaximumSize(new Dimension(905, 565));
        setMinimumSize(new Dimension(905, 565));

        panelArriba.setBackground(new Color(190, 191, 190));
        panelArriba.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        btMes.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        btMes.setText("Mes");
        btMes.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        btMes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btMesActionPerformed(evt);
            }
        });

        btDia.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        btDia.setText("Día");
        btDia.setBorder(new SoftBevelBorder(BevelBorder.RAISED));

        btHora.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        btHora.setText("Hora");
        btHora.setBorder(new SoftBevelBorder(BevelBorder.RAISED));

        btAnadir.setFont(new Font("Ubuntu", 1, 20)); // NOI18N
        btAnadir.setText("+");
        btAnadir.setBorder(new SoftBevelBorder(BevelBorder.RAISED));

        btAno.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        btAno.setText("Año");
        btAno.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        btAno.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAnoActionPerformed(evt);
            }
        });

        GroupLayout panelArribaLayout = new GroupLayout(panelArriba);
        panelArriba.setLayout(panelArribaLayout);
        panelArribaLayout.setHorizontalGroup(panelArribaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btAno, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMes, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDia, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btHora, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAnadir, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        panelArribaLayout.setVerticalGroup(panelArribaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArribaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, panelArribaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelArribaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btAno)
                            .addComponent(btMes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDia, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHora)))
                    .addComponent(btAnadir))
                .addContainerGap())
        );

        panelDerecha.setBackground(new Color(190, 191, 190));
        panelDerecha.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        periodoTiempo.setBackground(new Color(1, 1, 1));
        periodoTiempo.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        periodoTiempo.setForeground(new Color(1, 1, 1));
        periodoTiempo.setText("Periodo de tiempo");

        fechaInicio.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        fechaInicio.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fechaInicio.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                fechaInicioActionPerformed(evt);
            }
        });

        fechaFin.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        fechaFin.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tipoTarifa.setBackground(new Color(1, 1, 1));
        tipoTarifa.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        tipoTarifa.setForeground(new Color(1, 1, 1));
        tipoTarifa.setText("Tipo de tarifa");

        sinDiscriminacion.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        sinDiscriminacion.setText("Sin discriminación");
        sinDiscriminacion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                sinDiscriminacionActionPerformed(evt);
            }
        });

        discriminacion1.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        discriminacion1.setText("Discriminación 2");

        discriminacion2.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        discriminacion2.setText("Discriminación 1");

        renovable.setBackground(new Color(1, 1, 1));
        renovable.setFont(new Font("Ubuntu", 1, 18)); // NOI18N
        renovable.setForeground(new Color(1, 1, 1));
        renovable.setText("Renovable");

        soloRenovable.setFont(new Font("Ubuntu", 0, 18)); // NOI18N
        soloRenovable.setText("Solo renovables");
        soloRenovable.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                soloRenovableActionPerformed(evt);
            }
        });

        GroupLayout panelDerechaLayout = new GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(panelDerechaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDerechaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(renovable)
                    .addComponent(tipoTarifa)
                    .addComponent(periodoTiempo)
                    .addComponent(fechaFin, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaInicio, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDerechaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelDerechaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(sinDiscriminacion)
                            .addComponent(discriminacion2, GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.LEADING, panelDerechaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(soloRenovable))
                            .addComponent(discriminacion1, GroupLayout.Alignment.LEADING))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelDerechaLayout.setVerticalGroup(panelDerechaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(periodoTiempo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaFin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoTarifa)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sinDiscriminacion)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discriminacion2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discriminacion1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renovable)
                .addGap(18, 18, 18)
                .addComponent(soloRenovable)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        listaCompanias.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));
        listaCompanias.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelIzquierda.setViewportView(listaCompanias);

        panelNombre.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0), 2));

        labelNombre.setFont(new Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setForeground(new Color(16, 103, 218));
        labelNombre.setHorizontalAlignment(SwingConstants.CENTER);
        labelNombre.setText("COMPARADOR DE TARIFAS");

        GroupLayout panelNombreLayout = new GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(labelNombre)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        panelNombreLayout.setVerticalGroup(panelNombreLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIzquierda)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDerecha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(panelArriba, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNombre, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArriba, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panelIzquierda)
                    .addComponent(panelDerecha, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fechaInicioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_fechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicioActionPerformed

    private void btAnoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnoActionPerformed

    private void soloRenovableActionPerformed(ActionEvent evt) {//GEN-FIRST:event_soloRenovableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soloRenovableActionPerformed

    private void sinDiscriminacionActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sinDiscriminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinDiscriminacionActionPerformed

    private void btMesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
